name: 'Ansible Lint and Refactor'
description: 'A Github action for fixing Ansible-lint failures and refactoring Ansible playbooks and tasks.'
author: 'Your Name <your.email@example.com>'
branding:
  icon: 'box'
  color: 'green'

runs:
  using: 'docker'
  image: 'docker-ubuntu2204-ansible'

env:
  OLLAMA_API_BASE: 'http://ollama.ollama.svc.cluster.local:11434'
  MODEL: 'ollama/granite3-dense:8b'
  EDITOR_MODEL: 'ollama/granite3-dense:8b'
  PLAYBOOKS_DIR: 'playbooks/'
  TASKS_DIR: 'playbooks/tasks/'

jobs:
  ansible-lint-and-refactor:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Ansible Lint and Refactor
      run: |
        chmod +x /opt/ansible-venv/bin/ansible-lint-script.sh
        /opt/ansible-venv/bin/ansible-lint-script.sh
