---
name: Docker Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v4

      - name: Test building image.
        run: docker build -t docker-ansible .

      - name: list docker images
        run: docker images

      - name: Run the container
        run: |
          docker run --name test-container -d docker-ansible sleep infinity

      - name: Verify Ansible is accessible
        run: |
          docker exec test-container ansible --version

      - name: Stop and remove container
        run: docker rm -f test-container

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v4

      - name: Login to DockerHub.
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: quay.io/takinosh/ubuntu2410-ansible:${{ github.sha }}
